/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ArticleId = string;
export type Category = { 'mentalHealth' : null } |
  { 'sleep' : null } |
  { 'fitness' : null } |
  { 'nutrition' : null };
export interface WellnessArticle {
  'id' : ArticleId,
  'title' : string,
  'content' : string,
  'author' : string,
  'category' : Category,
}
export interface _SERVICE {
  'getAllArticles' : ActorMethod<[], Array<WellnessArticle>>,
  'getArticleById' : ActorMethod<[ArticleId], WellnessArticle>,
  'getArticlesByCategory' : ActorMethod<[Category], Array<WellnessArticle>>,
  'initializeContent' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];