/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ArticleId = IDL.Text;
export const Category = IDL.Variant({
  'mentalHealth' : IDL.Null,
  'sleep' : IDL.Null,
  'fitness' : IDL.Null,
  'nutrition' : IDL.Null,
});
export const WellnessArticle = IDL.Record({
  'id' : ArticleId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'category' : Category,
});

export const idlService = IDL.Service({
  'getAllArticles' : IDL.Func([], [IDL.Vec(WellnessArticle)], ['query']),
  'getArticleById' : IDL.Func([ArticleId], [WellnessArticle], ['query']),
  'getArticlesByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(WellnessArticle)],
      ['query'],
    ),
  'initializeContent' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ArticleId = IDL.Text;
  const Category = IDL.Variant({
    'mentalHealth' : IDL.Null,
    'sleep' : IDL.Null,
    'fitness' : IDL.Null,
    'nutrition' : IDL.Null,
  });
  const WellnessArticle = IDL.Record({
    'id' : ArticleId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'category' : Category,
  });
  
  return IDL.Service({
    'getAllArticles' : IDL.Func([], [IDL.Vec(WellnessArticle)], ['query']),
    'getArticleById' : IDL.Func([ArticleId], [WellnessArticle], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(WellnessArticle)],
        ['query'],
      ),
    'initializeContent' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };